'''Global Genetic Factors'''
SELECTION_FACTOR = 0.5  # Linear probability of distribution
MUTATION_FACTOR = 0.4
RECOMBINATION_FACTOR = 0.8

POPULATION_SIZE = 40
EVOLUTION_CYCLES = 120
FIELD_SIZE = 20
DRAW_EVERY_CYCLE = False
SHOW_PRODUCT_PATH = False

#PRODUCT_JSON = 'ProductsBig.json'
WORKSTATION_JSON = 'WorkstationsMid.json'

# Product Optimizer Constants
LISTS_PER_GENERATION = 5
PRODUCTS_PER_LIST = 16
PRODUCTS_PATH_LENGTH = 5
PRODUCTS_SELECTION_FACTOR = 0.2
PRODUCTS_MUTATION_FACTOR = 0.2