'''Global Genetic Factors'''
SELECTION_FACTOR = 0.85
MUTATION_FACTOR = 0.2
BREED_FACTOR = 1
RECOMBINATION_FACTOR = 0.1

POPULATION_SIZE = 50
EVOLUTION_CYCLES = 2000
MUTATION_ZERO_FACTOR = 3
FIELD_SIZE = 30
DRAW_EVERY_CYCLE = False

PRODUCT_JSON = 'Products.json'
WORKSTATION_JSON = 'WorkstationsBig.json'
